package [(${pojo.pojoPath})];

[# th:if="${parentPojoPath} ne null"]import [(${parentPojoPath})];[(${lineBreak})][/][# th:if="${voPath} ne null"]import [(${voPath})].*;[(${lineBreak})][/][# th:if="${dtoPath} ne null"]import [(${dtoPath})].*;[(${lineBreak})][/]import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.validation.constraints.*;
import javax.validation.*;
import java.io.Serializable;
import java.util.*;

/**
 * @Owner: [(${pojo.ownerUserId})]
 * @Description: generated by devtools
 */
@Data
@NoArgsConstructor
[# th:if="${not #lists.isEmpty(fields)}"]@AllArgsConstructor[(${lineBreak})][/]@ApiModel(description = "[(${pojo.pojoDesc})]")
public class [(${pojo.pojoName})][# th:if="${parentPojoName} ne null"] extends [(${parentPojoName})][/][# th:if="${parentPojoName} eq null"] implements Serializable[/] {
    [# th:each="field : ${fields}"]
    [(${field.templateAnnotation})]
    private [(${field.fieldType})] [(${field.fieldName})];[(${lineBreak})][/]
}