package [(${service.servicePath})];

import [(${voPath})].*;
import [(${dtoPath})].*;
import java.util.*;
[# th:each="dependency : ${dependencySet}"]
import [(${dependency})];
[/]
/**
 * @Owner: [(${service.ownerUserId})]
 * @Description: generated by devtools
 */
public interface [(${service.serviceName})] {
[# th:each="methodDetail : ${methodDetails}"]
    /**
     * [(${methodDetail.apiDesc})]
     */
    [(${methodDetail.dtoTemplateName})] [(${methodDetail.methodName})]([(${methodDetail.voTemplateName})])[# th:if="${methodDetail.methodException ne null}"] throws [(${methodDetail.methodException.key})][/];

[/]}